/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAbastecimentosRouteImport } from './routes/_authenticated/abastecimentos'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedAutorizacoesRouteImport } from './routes/_authenticated/autorizacoes'
import { Route as AuthenticatedCentrosCustoRouteImport } from './routes/_authenticated/centros-custo'
import { Route as AuthenticatedCombustiveisRouteImport } from './routes/_authenticated/combustiveis'
import { Route as AuthenticatedCondutoresRouteImport } from './routes/_authenticated/condutores'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedCotasRouteImport } from './routes/_authenticated/cotas'
import { Route as AuthenticatedEmpenhosRouteImport } from './routes/_authenticated/empenhos'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedManutencoesRouteImport } from './routes/_authenticated/manutencoes'
import { Route as AuthenticatedOrgaoRouteImport } from './routes/_authenticated/orgao'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPecasRouteImport } from './routes/_authenticated/pecas'
import { Route as AuthenticatedPlanosManutencaoRouteImport } from './routes/_authenticated/planos-manutencao'
import { Route as AuthenticatedPneusRouteImport } from './routes/_authenticated/pneus'
import { Route as AuthenticatedUnidadesRouteImport } from './routes/_authenticated/unidades'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedUtilizacaoRouteImport } from './routes/_authenticated/utilizacao'
import { Route as AuthenticatedVeiculosRouteImport } from './routes/_authenticated/veiculos'
import { Route as AuthenticatedVeiculoIdRouteImport } from './routes/_authenticated/veiculo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAbastecimentosRoute =
  AuthenticatedAbastecimentosRouteImport.update({
    id: '/abastecimentos',
    path: '/abastecimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutorizacoesRoute =
  AuthenticatedAutorizacoesRouteImport.update({
    id: '/autorizacoes',
    path: '/autorizacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentrosCustoRoute =
  AuthenticatedCentrosCustoRouteImport.update({
    id: '/centros-custo',
    path: '/centros-custo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCombustiveisRoute =
  AuthenticatedCombustiveisRouteImport.update({
    id: '/combustiveis',
    path: '/combustiveis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCondutoresRoute = AuthenticatedCondutoresRouteImport.update({
  id: '/condutores',
  path: '/condutores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCotasRoute = AuthenticatedCotasRouteImport.update({
  id: '/cotas',
  path: '/cotas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpenhosRoute = AuthenticatedEmpenhosRouteImport.update({
  id: '/empenhos',
  path: '/empenhos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManutencoesRoute =
  AuthenticatedManutencoesRouteImport.update({
    id: '/manutencoes',
    path: '/manutencoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgaoRoute = AuthenticatedOrgaoRouteImport.update({
  id: '/orgao',
  path: '/orgao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPecasRoute = AuthenticatedPecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosManutencaoRoute =
  AuthenticatedPlanosManutencaoRouteImport.update({
    id: '/planos-manutencao',
    path: '/planos-manutencao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPneusRoute = AuthenticatedPneusRouteImport.update({
  id: '/pneus',
  path: '/pneus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnidadesRoute = AuthenticatedUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUtilizacaoRoute = AuthenticatedUtilizacaoRouteImport.update({
  id: '/utilizacao',
  path: '/utilizacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeiculosRoute = AuthenticatedVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeiculoIdRoute = AuthenticatedVeiculoIdRouteImport.update({
  id: '/veiculo/$id',
  path: '/veiculo/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/abastecimentos': typeof AuthenticatedAbastecimentosRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/autorizacoes': typeof AuthenticatedAutorizacoesRoute
  '/centros-custo': typeof AuthenticatedCentrosCustoRoute
  '/combustiveis': typeof AuthenticatedCombustiveisRoute
  '/condutores': typeof AuthenticatedCondutoresRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/cotas': typeof AuthenticatedCotasRoute
  '/empenhos': typeof AuthenticatedEmpenhosRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/manutencoes': typeof AuthenticatedManutencoesRoute
  '/orgao': typeof AuthenticatedOrgaoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/planos-manutencao': typeof AuthenticatedPlanosManutencaoRoute
  '/pneus': typeof AuthenticatedPneusRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/utilizacao': typeof AuthenticatedUtilizacaoRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/veiculo/$id': typeof AuthenticatedVeiculoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/abastecimentos': typeof AuthenticatedAbastecimentosRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/autorizacoes': typeof AuthenticatedAutorizacoesRoute
  '/centros-custo': typeof AuthenticatedCentrosCustoRoute
  '/combustiveis': typeof AuthenticatedCombustiveisRoute
  '/condutores': typeof AuthenticatedCondutoresRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/cotas': typeof AuthenticatedCotasRoute
  '/empenhos': typeof AuthenticatedEmpenhosRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/manutencoes': typeof AuthenticatedManutencoesRoute
  '/orgao': typeof AuthenticatedOrgaoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/planos-manutencao': typeof AuthenticatedPlanosManutencaoRoute
  '/pneus': typeof AuthenticatedPneusRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/utilizacao': typeof AuthenticatedUtilizacaoRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/veiculo/$id': typeof AuthenticatedVeiculoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/abastecimentos': typeof AuthenticatedAbastecimentosRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/autorizacoes': typeof AuthenticatedAutorizacoesRoute
  '/_authenticated/centros-custo': typeof AuthenticatedCentrosCustoRoute
  '/_authenticated/combustiveis': typeof AuthenticatedCombustiveisRoute
  '/_authenticated/condutores': typeof AuthenticatedCondutoresRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/cotas': typeof AuthenticatedCotasRoute
  '/_authenticated/empenhos': typeof AuthenticatedEmpenhosRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/manutencoes': typeof AuthenticatedManutencoesRoute
  '/_authenticated/orgao': typeof AuthenticatedOrgaoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pecas': typeof AuthenticatedPecasRoute
  '/_authenticated/planos-manutencao': typeof AuthenticatedPlanosManutencaoRoute
  '/_authenticated/pneus': typeof AuthenticatedPneusRoute
  '/_authenticated/unidades': typeof AuthenticatedUnidadesRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/utilizacao': typeof AuthenticatedUtilizacaoRoute
  '/_authenticated/veiculos': typeof AuthenticatedVeiculosRoute
  '/_authenticated/veiculo/$id': typeof AuthenticatedVeiculoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/abastecimentos'
    | '/alertas'
    | '/autorizacoes'
    | '/centros-custo'
    | '/combustiveis'
    | '/condutores'
    | '/contratos'
    | '/cotas'
    | '/empenhos'
    | '/fornecedores'
    | '/manutencoes'
    | '/orgao'
    | '/painel'
    | '/pecas'
    | '/planos-manutencao'
    | '/pneus'
    | '/unidades'
    | '/usuarios'
    | '/utilizacao'
    | '/veiculos'
    | '/veiculo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/abastecimentos'
    | '/alertas'
    | '/autorizacoes'
    | '/centros-custo'
    | '/combustiveis'
    | '/condutores'
    | '/contratos'
    | '/cotas'
    | '/empenhos'
    | '/fornecedores'
    | '/manutencoes'
    | '/orgao'
    | '/painel'
    | '/pecas'
    | '/planos-manutencao'
    | '/pneus'
    | '/unidades'
    | '/usuarios'
    | '/utilizacao'
    | '/veiculos'
    | '/veiculo/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/abastecimentos'
    | '/_authenticated/alertas'
    | '/_authenticated/autorizacoes'
    | '/_authenticated/centros-custo'
    | '/_authenticated/combustiveis'
    | '/_authenticated/condutores'
    | '/_authenticated/contratos'
    | '/_authenticated/cotas'
    | '/_authenticated/empenhos'
    | '/_authenticated/fornecedores'
    | '/_authenticated/manutencoes'
    | '/_authenticated/orgao'
    | '/_authenticated/painel'
    | '/_authenticated/pecas'
    | '/_authenticated/planos-manutencao'
    | '/_authenticated/pneus'
    | '/_authenticated/unidades'
    | '/_authenticated/usuarios'
    | '/_authenticated/utilizacao'
    | '/_authenticated/veiculos'
    | '/_authenticated/veiculo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/abastecimentos': {
      id: '/_authenticated/abastecimentos'
      path: '/abastecimentos'
      fullPath: '/abastecimentos'
      preLoaderRoute: typeof AuthenticatedAbastecimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autorizacoes': {
      id: '/_authenticated/autorizacoes'
      path: '/autorizacoes'
      fullPath: '/autorizacoes'
      preLoaderRoute: typeof AuthenticatedAutorizacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-custo': {
      id: '/_authenticated/centros-custo'
      path: '/centros-custo'
      fullPath: '/centros-custo'
      preLoaderRoute: typeof AuthenticatedCentrosCustoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/combustiveis': {
      id: '/_authenticated/combustiveis'
      path: '/combustiveis'
      fullPath: '/combustiveis'
      preLoaderRoute: typeof AuthenticatedCombustiveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/condutores': {
      id: '/_authenticated/condutores'
      path: '/condutores'
      fullPath: '/condutores'
      preLoaderRoute: typeof AuthenticatedCondutoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotas': {
      id: '/_authenticated/cotas'
      path: '/cotas'
      fullPath: '/cotas'
      preLoaderRoute: typeof AuthenticatedCotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empenhos': {
      id: '/_authenticated/empenhos'
      path: '/empenhos'
      fullPath: '/empenhos'
      preLoaderRoute: typeof AuthenticatedEmpenhosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencoes': {
      id: '/_authenticated/manutencoes'
      path: '/manutencoes'
      fullPath: '/manutencoes'
      preLoaderRoute: typeof AuthenticatedManutencoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgao': {
      id: '/_authenticated/orgao'
      path: '/orgao'
      fullPath: '/orgao'
      preLoaderRoute: typeof AuthenticatedOrgaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pecas': {
      id: '/_authenticated/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof AuthenticatedPecasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos-manutencao': {
      id: '/_authenticated/planos-manutencao'
      path: '/planos-manutencao'
      fullPath: '/planos-manutencao'
      preLoaderRoute: typeof AuthenticatedPlanosManutencaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pneus': {
      id: '/_authenticated/pneus'
      path: '/pneus'
      fullPath: '/pneus'
      preLoaderRoute: typeof AuthenticatedPneusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unidades': {
      id: '/_authenticated/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof AuthenticatedUnidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/utilizacao': {
      id: '/_authenticated/utilizacao'
      path: '/utilizacao'
      fullPath: '/utilizacao'
      preLoaderRoute: typeof AuthenticatedUtilizacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculos': {
      id: '/_authenticated/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedVeiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculo/$id': {
      id: '/_authenticated/veiculo/$id'
      path: '/veiculo/$id'
      fullPath: '/veiculo/$id'
      preLoaderRoute: typeof AuthenticatedVeiculoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbastecimentosRoute: typeof AuthenticatedAbastecimentosRoute
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAutorizacoesRoute: typeof AuthenticatedAutorizacoesRoute
  AuthenticatedCentrosCustoRoute: typeof AuthenticatedCentrosCustoRoute
  AuthenticatedCombustiveisRoute: typeof AuthenticatedCombustiveisRoute
  AuthenticatedCondutoresRoute: typeof AuthenticatedCondutoresRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedCotasRoute: typeof AuthenticatedCotasRoute
  AuthenticatedEmpenhosRoute: typeof AuthenticatedEmpenhosRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedManutencoesRoute: typeof AuthenticatedManutencoesRoute
  AuthenticatedOrgaoRoute: typeof AuthenticatedOrgaoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPecasRoute: typeof AuthenticatedPecasRoute
  AuthenticatedPlanosManutencaoRoute: typeof AuthenticatedPlanosManutencaoRoute
  AuthenticatedPneusRoute: typeof AuthenticatedPneusRoute
  AuthenticatedUnidadesRoute: typeof AuthenticatedUnidadesRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedUtilizacaoRoute: typeof AuthenticatedUtilizacaoRoute
  AuthenticatedVeiculosRoute: typeof AuthenticatedVeiculosRoute
  AuthenticatedVeiculoIdRoute: typeof AuthenticatedVeiculoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbastecimentosRoute: AuthenticatedAbastecimentosRoute,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAutorizacoesRoute: AuthenticatedAutorizacoesRoute,
  AuthenticatedCentrosCustoRoute: AuthenticatedCentrosCustoRoute,
  AuthenticatedCombustiveisRoute: AuthenticatedCombustiveisRoute,
  AuthenticatedCondutoresRoute: AuthenticatedCondutoresRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedCotasRoute: AuthenticatedCotasRoute,
  AuthenticatedEmpenhosRoute: AuthenticatedEmpenhosRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedManutencoesRoute: AuthenticatedManutencoesRoute,
  AuthenticatedOrgaoRoute: AuthenticatedOrgaoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPecasRoute: AuthenticatedPecasRoute,
  AuthenticatedPlanosManutencaoRoute: AuthenticatedPlanosManutencaoRoute,
  AuthenticatedPneusRoute: AuthenticatedPneusRoute,
  AuthenticatedUnidadesRoute: AuthenticatedUnidadesRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedUtilizacaoRoute: AuthenticatedUtilizacaoRoute,
  AuthenticatedVeiculosRoute: AuthenticatedVeiculosRoute,
  AuthenticatedVeiculoIdRoute: AuthenticatedVeiculoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
