/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCombustiveisRouteImport } from './routes/_authenticated/combustiveis'
import { Route as AuthenticatedOrgaoRouteImport } from './routes/_authenticated/orgao'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedUnidadesRouteImport } from './routes/_authenticated/unidades'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedVeiculosRouteImport } from './routes/_authenticated/veiculos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCombustiveisRoute =
  AuthenticatedCombustiveisRouteImport.update({
    id: '/combustiveis',
    path: '/combustiveis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgaoRoute = AuthenticatedOrgaoRouteImport.update({
  id: '/orgao',
  path: '/orgao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnidadesRoute = AuthenticatedUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeiculosRoute = AuthenticatedVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/combustiveis': typeof AuthenticatedCombustiveisRoute
  '/orgao': typeof AuthenticatedOrgaoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/combustiveis': typeof AuthenticatedCombustiveisRoute
  '/orgao': typeof AuthenticatedOrgaoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/combustiveis': typeof AuthenticatedCombustiveisRoute
  '/_authenticated/orgao': typeof AuthenticatedOrgaoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/unidades': typeof AuthenticatedUnidadesRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/veiculos': typeof AuthenticatedVeiculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/combustiveis'
    | '/orgao'
    | '/painel'
    | '/unidades'
    | '/usuarios'
    | '/veiculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/combustiveis'
    | '/orgao'
    | '/painel'
    | '/unidades'
    | '/usuarios'
    | '/veiculos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/combustiveis'
    | '/_authenticated/orgao'
    | '/_authenticated/painel'
    | '/_authenticated/unidades'
    | '/_authenticated/usuarios'
    | '/_authenticated/veiculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/combustiveis': {
      id: '/_authenticated/combustiveis'
      path: '/combustiveis'
      fullPath: '/combustiveis'
      preLoaderRoute: typeof AuthenticatedCombustiveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orgao': {
      id: '/_authenticated/orgao'
      path: '/orgao'
      fullPath: '/orgao'
      preLoaderRoute: typeof AuthenticatedOrgaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unidades': {
      id: '/_authenticated/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof AuthenticatedUnidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculos': {
      id: '/_authenticated/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedVeiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCombustiveisRoute: typeof AuthenticatedCombustiveisRoute
  AuthenticatedOrgaoRoute: typeof AuthenticatedOrgaoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedUnidadesRoute: typeof AuthenticatedUnidadesRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVeiculosRoute: typeof AuthenticatedVeiculosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCombustiveisRoute: AuthenticatedCombustiveisRoute,
  AuthenticatedOrgaoRoute: AuthenticatedOrgaoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedUnidadesRoute: AuthenticatedUnidadesRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVeiculosRoute: AuthenticatedVeiculosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
