REVOKE EXECUTE ON FUNCTION public.next_org_code(uuid, text, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_vehicle_usage() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.apply_usage_km() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_fuel_authorization() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_fueling_authorization() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_fuel_authorization_usage() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.fuel_limit_breach(uuid, uuid, uuid, numeric, timestamptz) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.expire_fuel_authorizations() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_manage_fleet() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.unit_scope_ok(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_operate_usage() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.apply_fueling_meters() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.write_audit_log() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.seed_fuel_types() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_super_admin(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.current_org_id() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.my_unit_id() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_write() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_manage_users() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_register_fueling() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_cancel_fueling() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_fuel_vehicle(uuid) FROM PUBLIC, anon;